# Generated by Django 5.1.1 on 2024-09-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('math_marks', models.FloatField()),
                ('science_marks', models.FloatField()),
                ('english_marks', models.FloatField()),
            ],
        ),
    ]
